const COFID_URL = 'https://www.gov.uk/government/publications/composition-of-foods-integrated-dataset-cofid';
const BNF_URL = 'https://www.nutrition.org.uk/creating-a-healthy-diet/portion-sizes/';
const USDA_URL = 'https://fdc.nal.usda.gov/download-datasets/';
const HIGATES_URL = 'https://www.bradleysfoods.co.uk/files/88493f4a-5a8c-4e47-9d89-ab1300dfc834/Higate%20Plain%20Flapjack.pdf';
const VEETEE_URL = 'https://www.ocado.com/products/veetee-heat-eat-sticky-rice/637993011';
const MORRISONS_URL = 'https://www.grocefully.com/uk/product/morrisons/morrisons-savers-british-beef-mince-25-fat-500g-113834538';

// Practical starter references, not measured portions. Values are per 100 g/ml;
// the examples follow BNF portion guidance and UK CoFID values where available.
// Branded items retain the label values and package size as distinct evidence.
const FOOD_GUIDE = [
  { id: 'veetee-sticky-rice', name: 'Veetee Sticky Rice', brand: 'Veetee', aliases: ['Veetee sticky rice', 'Veetee perfectly sticky rice', 'sticky rice Veetee', 'Veetee steam filtered sticky rice'], category: 'Grains', unit: 'g', kcalPer100: 152, proteinPer100: 2.3, carbsPer100: 31.7, fatPer100: 1.8, defaultPortion: 300, portionLabel: 'one 300 g pot (pack shown contains two)', packageWeight: 600, caloriesPerServing: 456, source: 'Ocado product nutrition listing', sourceType: 'branded product listing', sourceUrl: VEETEE_URL, confidence: 'high', evidence: [{ value: 152, unit: 'kcal/100g', source: 'Ocado Veetee sticky rice listing', url: VEETEE_URL }, { value: 300, unit: 'g pot', source: 'Two 300 g pots / 600 g pack shown in photo', url: '' }] },
  { id: 'higates-plain-flapjack', name: 'Higates Plain & Delicious Flapjack', brand: 'Higates', aliases: ['Higates flapjack', 'Higates plain flapjack', 'Higates Flapjack Plain and Delicious', 'Highates flapjack', 'Higates Original Recipe Flapjack', 'On the Go Fuel Higates Flapjack'], category: 'Snacks', unit: 'g', kcalPer100: 443, proteinPer100: 4.76, carbsPer100: 56.31, fatPer100: 22.12, defaultPortion: 120, portionLabel: '120 g pack shown', packageWeight: 120, caloriesPerServing: 532, source: 'Higates product label/specification', sourceType: 'manufacturer label', sourceUrl: HIGATES_URL, confidence: 'high', evidence: [{ value: 443, unit: 'kcal/100g', source: 'Higates product label/specification', url: HIGATES_URL }, { value: 120, unit: 'g pack', source: 'Package shown in your photo', url: '' }] },
  { id: 'morrisons-savers-beef-mince-25', name: 'Morrisons Savers British Beef Mince 25% Fat', brand: 'Morrisons', aliases: ['Morrisons 25% mince', 'Morrisons 25 percent beef mince', 'Morrisons Savers beef mince', 'Morrisons beef mince 500g', 'Morrisons mince 25% fat'], barcode: '', category: 'Meat', unit: 'g', kcalPer100: 285, proteinPer100: 16.9, carbsPer100: 0.2, fatPer100: 24, defaultPortion: 125, portionLabel: '125 g raw portion', packageWeight: 500, caloriesPerServing: 356, source: 'Morrisons 500 g product listing (aggregated nutrition data)', sourceType: 'branded product listing', sourceUrl: MORRISONS_URL, confidence: 'medium', evidence: [{ value: 285, unit: 'kcal/100g', source: 'Morrisons 500 g product listing (aggregated data)', url: MORRISONS_URL }, { value: 500, unit: 'g pack', source: 'Product pack size', url: MORRISONS_URL }] },
  { id: 'plain-flapjack-cofid', name: 'Plain flapjack', brand: '', aliases: ['flapjack', 'oat flapjack', 'plain oat bar', 'oat bar flapjack'], category: 'Snacks', unit: 'g', kcalPer100: 434, proteinPer100: 5.1, carbsPer100: 55.7, fatPer100: 22.8, defaultPortion: 70, portionLabel: 'typical 70 g retail bar', packageWeight: null, caloriesPerServing: 304, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 434, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }, { value: 70, unit: 'g serving', source: 'Typical retail bar reference', url: BNF_URL }] },
  { id: 'beef-steak-mince-25-generic', name: 'Beef mince, 25% fat (raw)', brand: '', aliases: ['25% fat mince', '25 percent fat beef mince', 'high fat beef mince', 'beef mince raw 25 fat'], category: 'Meat', unit: 'g', kcalPer100: 285, proteinPer100: 16.9, carbsPer100: 0.2, fatPer100: 24, defaultPortion: 125, portionLabel: '125 g raw portion', packageWeight: null, caloriesPerServing: 356, source: 'Typical 25% fat product label value', sourceType: 'branded-product reference', sourceUrl: MORRISONS_URL, confidence: 'medium', evidence: [{ value: 285, unit: 'kcal/100g', source: 'Morrisons Savers 25% mince reference', url: MORRISONS_URL }, { value: 125, unit: 'g serving', source: 'British Nutrition Foundation portion guide', url: BNF_URL }] },
  { id: 'chicken-breast-grilled', name: 'Chicken breast, grilled', brand: '', aliases: ['chicken breast', 'grilled chicken breast', 'roast chicken breast', 'chicken breast cooked'], category: 'Meat', unit: 'g', kcalPer100: 148, proteinPer100: 31, carbsPer100: 0, fatPer100: 3.6, defaultPortion: 120, portionLabel: 'one hand-sized breast (~120 g)', packageWeight: null, caloriesPerServing: 178, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 178, unit: 'kcal/120g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'chicken-roast', name: 'Roast chicken (white meat)', brand: '', aliases: ['roast chicken', 'roasted chicken'], category: 'Meat', unit: 'g', kcalPer100: 153, proteinPer100: 29, carbsPer100: 0, fatPer100: 3.2, defaultPortion: 100, portionLabel: '100 g serving', packageWeight: null, caloriesPerServing: 153, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 153, unit: 'kcal/100g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'rice-white-cooked', name: 'White rice, cooked', brand: '', aliases: ['rice', 'cooked rice', 'boiled rice', 'white rice'], category: 'Grains', unit: 'g', kcalPer100: 131, proteinPer100: 2.7, carbsPer100: 28.2, fatPer100: 0.3, defaultPortion: 180, portionLabel: 'two cupped handfuls (~180 g cooked)', packageWeight: null, caloriesPerServing: 236, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 236, unit: 'kcal/180g cooked', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'pasta-plain-cooked', name: 'Plain pasta, cooked', brand: '', aliases: ['pasta', 'cooked pasta', 'boiled pasta', 'spaghetti cooked'], category: 'Grains', unit: 'g', kcalPer100: 150, proteinPer100: 5.5, carbsPer100: 29, fatPer100: 0.9, defaultPortion: 180, portionLabel: 'two cupped handfuls (~180 g cooked)', packageWeight: null, caloriesPerServing: 270, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 270, unit: 'kcal/180g cooked', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'chips-fried', name: 'French fries / fried chips', brand: '', aliases: ['french fries', 'fries', 'chips', 'deep fried chips', 'takeaway chips'], category: 'Grains', unit: 'g', kcalPer100: 312, proteinPer100: 3.4, carbsPer100: 41, fatPer100: 15, defaultPortion: 165, portionLabel: 'medium side portion (~165 g)', packageWeight: null, caloriesPerServing: 515, source: 'USDA FoodData Central, generic restaurant fries', sourceType: 'food composition dataset', sourceUrl: USDA_URL, confidence: 'medium', evidence: [{ value: 312, unit: 'kcal/100g', source: 'USDA FoodData Central', url: USDA_URL }] },
  { id: 'chips-oven-cooked', name: 'Oven chips', brand: '', aliases: ['oven chips', 'oven fries'], category: 'Grains', unit: 'g', kcalPer100: 156, proteinPer100: 2.7, carbsPer100: 25, fatPer100: 4.4, defaultPortion: 165, portionLabel: 'two handfuls (~165 g)', packageWeight: null, caloriesPerServing: 257, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 257, unit: 'kcal/165g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'baked-potato', name: 'Baked potato', brand: '', aliases: ['jacket potato', 'baked potato with skin'], category: 'Vegetables', unit: 'g', kcalPer100: 97, proteinPer100: 2.5, carbsPer100: 21, fatPer100: 0.1, defaultPortion: 220, portionLabel: 'one fist-sized potato (~220 g)', packageWeight: null, caloriesPerServing: 213, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 213, unit: 'kcal/220g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'potato-new-boiled', name: 'New potatoes, boiled', brand: '', aliases: ['boiled potatoes', 'new potatoes', 'potato boiled'], category: 'Vegetables', unit: 'g', kcalPer100: 68, proteinPer100: 1.8, carbsPer100: 15, fatPer100: 0.1, defaultPortion: 175, portionLabel: 'about six small potatoes (~175 g)', packageWeight: null, caloriesPerServing: 119, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 119, unit: 'kcal/175g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'cheddar', name: 'Cheddar cheese', brand: '', aliases: ['cheddar', 'grated cheddar', 'cheese cheddar'], category: 'Dairy', unit: 'g', kcalPer100: 417, proteinPer100: 25.4, carbsPer100: 0.1, fatPer100: 34.9, defaultPortion: 30, portionLabel: 'two-thumb piece (~30 g)', packageWeight: null, caloriesPerServing: 125, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 125, unit: 'kcal/30g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'egg-boiled', name: 'Boiled egg', brand: '', aliases: ['egg', 'eggs', 'boiled eggs', 'one egg'], category: 'Protein', unit: 'g', kcalPer100: 143, proteinPer100: 12.6, carbsPer100: 0.7, fatPer100: 9.5, defaultPortion: 60, portionLabel: 'one medium egg (~60 g)', packageWeight: null, caloriesPerServing: 86, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 86, unit: 'kcal/60g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'oats-porridge-dry', name: 'Porridge oats (dry)', brand: '', aliases: ['oats', 'porridge oats', 'oatmeal', 'rolled oats'], category: 'Grains', unit: 'g', kcalPer100: 380, proteinPer100: 13.2, carbsPer100: 67.7, fatPer100: 6.5, defaultPortion: 45, portionLabel: 'one bowl portion, dry oats (~45 g)', packageWeight: null, caloriesPerServing: 171, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 171, unit: 'kcal/45g dry', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'bread-wholemeal', name: 'Wholemeal bread', brand: '', aliases: ['wholemeal bread slice', 'brown bread', 'whole grain bread'], category: 'Grains', unit: 'g', kcalPer100: 218, proteinPer100: 9.2, carbsPer100: 38.5, fatPer100: 3.5, defaultPortion: 40, portionLabel: 'one medium slice (~40 g)', packageWeight: null, caloriesPerServing: 87, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 87, unit: 'kcal/40g slice', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'baguette', name: 'Baguette', brand: '', aliases: ['white baguette'], category: 'Grains', unit: 'g', kcalPer100: 263, proteinPer100: 8.7, carbsPer100: 52, fatPer100: 1.2, defaultPortion: 70, portionLabel: 'half a small baguette (~70 g)', packageWeight: null, caloriesPerServing: 184, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 184, unit: 'kcal/70g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'peanut-butter', name: 'Peanut butter', brand: '', aliases: ['peanut butter spoon', 'smooth peanut butter', 'crunchy peanut butter'], category: 'Snacks', unit: 'g', kcalPer100: 605, proteinPer100: 25, carbsPer100: 11, fatPer100: 50, defaultPortion: 20, portionLabel: 'one tablespoon (~20 g)', packageWeight: null, caloriesPerServing: 121, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 121, unit: 'kcal/20g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'baked-beans', name: 'Baked beans', brand: '', aliases: ['beans', 'tinned baked beans', 'canned baked beans'], category: 'Protein', unit: 'g', kcalPer100: 81, proteinPer100: 5.2, carbsPer100: 12.5, fatPer100: 0.5, defaultPortion: 200, portionLabel: 'half a 400 g tin (~200 g)', packageWeight: null, caloriesPerServing: 162, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 162, unit: 'kcal/200g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'tuna-canned', name: 'Canned tuna', brand: '', aliases: ['tuna', 'tinned tuna', 'tuna in spring water', 'tuna in brine'], category: 'Fish', unit: 'g', kcalPer100: 109, proteinPer100: 25.5, carbsPer100: 0, fatPer100: 0.8, defaultPortion: 120, portionLabel: 'one drained can (~120 g)', packageWeight: null, caloriesPerServing: 131, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 131, unit: 'kcal/120g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'peanut-nuts', name: 'Mixed nuts', brand: '', aliases: ['nuts', 'handful of nuts', 'unsalted nuts'], category: 'Snacks', unit: 'g', kcalPer100: 625, proteinPer100: 20, carbsPer100: 21, fatPer100: 54, defaultPortion: 20, portionLabel: 'small palmful (~20 g)', packageWeight: null, caloriesPerServing: 125, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 125, unit: 'kcal/20g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'olive-oil', name: 'Olive oil', brand: '', aliases: ['oil', 'cooking oil', 'vegetable oil'], category: 'Cooking ingredients', unit: 'ml', kcalPer100: 884, proteinPer100: 0, carbsPer100: 0, fatPer100: 100, defaultPortion: 5, portionLabel: 'one teaspoon (~5 ml)', packageWeight: null, caloriesPerServing: 27, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 27, unit: 'kcal/5ml', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'milk-semi-skimmed', name: 'Semi-skimmed milk', brand: '', aliases: ['milk', 'semi skimmed milk', 'semi-skimmed milk'], category: 'Drinks', unit: 'ml', kcalPer100: 46, proteinPer100: 3.6, carbsPer100: 4.8, fatPer100: 1.7, defaultPortion: 200, portionLabel: 'one glass (~200 ml)', packageWeight: null, caloriesPerServing: 92, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 92, unit: 'kcal/200ml', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'milk-whole', name: 'Whole milk', brand: '', aliases: ['whole milk glass'], category: 'Drinks', unit: 'ml', kcalPer100: 63, proteinPer100: 3.3, carbsPer100: 4.7, fatPer100: 3.6, defaultPortion: 200, portionLabel: 'one glass (~200 ml)', packageWeight: null, caloriesPerServing: 126, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 126, unit: 'kcal/200ml', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'coffee-black', name: 'Black coffee', brand: '', aliases: ['coffee', 'plain coffee', 'americano black', 'espresso'], category: 'Drinks', unit: 'ml', kcalPer100: 1, proteinPer100: 0.1, carbsPer100: 0, fatPer100: 0, defaultPortion: 240, portionLabel: 'one mug, black (~240 ml)', packageWeight: null, caloriesPerServing: 2, source: 'USDA FoodData Central', sourceType: 'food composition dataset', sourceUrl: USDA_URL, confidence: 'medium', evidence: [{ value: 2, unit: 'kcal/cup', source: 'USDA FoodData Central', url: USDA_URL }] },
  { id: 'tea-black', name: 'Black tea', brand: '', aliases: ['tea', 'plain tea', 'black tea'], category: 'Drinks', unit: 'ml', kcalPer100: 0.2, proteinPer100: 0, carbsPer100: 0, fatPer100: 0, defaultPortion: 240, portionLabel: 'one mug, without milk or sugar (~240 ml)', packageWeight: null, caloriesPerServing: 1, source: 'USDA FoodData Central', sourceType: 'food composition dataset', sourceUrl: USDA_URL, confidence: 'medium', evidence: [{ value: 1, unit: 'kcal/cup', source: 'USDA FoodData Central', url: USDA_URL }] },
  { id: 'cola', name: 'Cola', brand: '', aliases: ['coca cola', 'soft drink cola', 'regular cola'], category: 'Drinks', unit: 'ml', kcalPer100: 42, proteinPer100: 0, carbsPer100: 10.6, fatPer100: 0, defaultPortion: 330, portionLabel: 'one 330 ml can', packageWeight: 330, caloriesPerServing: 139, source: 'Typical full-sugar cola label', sourceType: 'branded-product reference', sourceUrl: USDA_URL, confidence: 'medium', evidence: [{ value: 42, unit: 'kcal/100ml', source: 'Typical full-sugar cola label', url: USDA_URL }] },
  { id: 'orange-juice', name: 'Orange juice', brand: '', aliases: ['fresh orange juice', 'orange juice drink'], category: 'Drinks', unit: 'ml', kcalPer100: 45, proteinPer100: 0.7, carbsPer100: 10, fatPer100: 0.2, defaultPortion: 150, portionLabel: 'small glass (~150 ml)', packageWeight: null, caloriesPerServing: 68, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 68, unit: 'kcal/150ml', source: 'British Nutrition Foundation portion guide', url: BNF_URL }] },
  { id: 'apple-fruit', name: 'Apple', brand: '', aliases: ['apple raw', 'one apple'], category: 'Fruit', unit: 'g', kcalPer100: 52, proteinPer100: 0.3, carbsPer100: 13.8, fatPer100: 0.2, defaultPortion: 150, portionLabel: 'one medium apple (~150 g)', packageWeight: null, caloriesPerServing: 78, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 52, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'banana-fruit', name: 'Banana', brand: '', aliases: ['one banana', 'banana raw'], category: 'Fruit', unit: 'g', kcalPer100: 89, proteinPer100: 1.1, carbsPer100: 22.8, fatPer100: 0.3, defaultPortion: 120, portionLabel: 'one medium banana (~120 g edible)', packageWeight: null, caloriesPerServing: 107, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 89, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'orange-fruit', name: 'Orange', brand: '', aliases: ['one orange', 'orange raw'], category: 'Fruit', unit: 'g', kcalPer100: 47, proteinPer100: 0.9, carbsPer100: 11.8, fatPer100: 0.1, defaultPortion: 130, portionLabel: 'one medium orange (~130 g edible)', packageWeight: null, caloriesPerServing: 61, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 47, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'grapes-fruit', name: 'Grapes', brand: '', aliases: ['grape', 'bunch of grapes'], category: 'Fruit', unit: 'g', kcalPer100: 69, proteinPer100: 0.7, carbsPer100: 18.1, fatPer100: 0.2, defaultPortion: 80, portionLabel: 'one fruit portion (~80 g)', packageWeight: null, caloriesPerServing: 55, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 69, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'strawberries', name: 'Strawberries', brand: '', aliases: ['strawberry', 'fresh strawberries'], category: 'Fruit', unit: 'g', kcalPer100: 32, proteinPer100: 0.7, carbsPer100: 7.7, fatPer100: 0.3, defaultPortion: 80, portionLabel: 'one fruit portion (~80 g)', packageWeight: null, caloriesPerServing: 26, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 32, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'tomato', name: 'Tomato', brand: '', aliases: ['tomatoes', 'one tomato', 'cherry tomatoes'], category: 'Vegetables', unit: 'g', kcalPer100: 18, proteinPer100: 0.9, carbsPer100: 3.9, fatPer100: 0.2, defaultPortion: 80, portionLabel: 'one fruit/vegetable portion (~80 g)', packageWeight: null, caloriesPerServing: 14, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 18, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'broccoli', name: 'Broccoli', brand: '', aliases: ['broccoli florets', 'cooked broccoli'], category: 'Vegetables', unit: 'g', kcalPer100: 34, proteinPer100: 2.8, carbsPer100: 6.6, fatPer100: 0.4, defaultPortion: 80, portionLabel: 'one vegetable portion (~80 g)', packageWeight: null, caloriesPerServing: 27, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 34, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'carrot', name: 'Carrot', brand: '', aliases: ['carrots', 'raw carrot', 'cooked carrot'], category: 'Vegetables', unit: 'g', kcalPer100: 41, proteinPer100: 0.9, carbsPer100: 9.6, fatPer100: 0.2, defaultPortion: 80, portionLabel: 'one vegetable portion (~80 g)', packageWeight: null, caloriesPerServing: 33, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 41, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'lettuce-salad', name: 'Lettuce / salad leaves', brand: '', aliases: ['lettuce', 'salad leaves', 'green salad'], category: 'Vegetables', unit: 'g', kcalPer100: 15, proteinPer100: 1.4, carbsPer100: 2.9, fatPer100: 0.2, defaultPortion: 50, portionLabel: 'small side salad (~50 g)', packageWeight: null, caloriesPerServing: 8, source: 'CoFID 2021 average', sourceType: 'UK food composition dataset', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 15, unit: 'kcal/100g', source: 'CoFID 2021', url: COFID_URL }] },
  { id: 'plain-yogurt', name: 'Plain low-fat yoghurt', brand: '', aliases: ['plain yogurt', 'plain yoghurt', 'low fat yogurt'], category: 'Dairy', unit: 'g', kcalPer100: 57, proteinPer100: 5.3, carbsPer100: 7, fatPer100: 1.5, defaultPortion: 120, portionLabel: 'small bowl (~120 g)', packageWeight: null, caloriesPerServing: 68, source: 'British Nutrition Foundation portion guide', sourceType: 'portion guide', sourceUrl: BNF_URL, confidence: 'medium', evidence: [{ value: 68, unit: 'kcal/120g', source: 'British Nutrition Foundation', url: BNF_URL }] },
  { id: 'crisps-potato', name: 'Potato crisps', brand: '', aliases: ['crisps', 'potato chips', 'packet crisps'], category: 'Snacks', unit: 'g', kcalPer100: 536, proteinPer100: 6.5, carbsPer100: 52, fatPer100: 34, defaultPortion: 25, portionLabel: 'small bag (~25 g)', packageWeight: 25, caloriesPerServing: 134, source: 'Typical UK nutrition label value', sourceType: 'branded-product reference', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 536, unit: 'kcal/100g', source: 'Typical plain potato crisp value', url: COFID_URL }] },
  { id: 'milk-chocolate', name: 'Milk chocolate', brand: '', aliases: ['chocolate', 'chocolate bar', 'milk chocolate bar'], category: 'Snacks', unit: 'g', kcalPer100: 535, proteinPer100: 7.3, carbsPer100: 59, fatPer100: 30, defaultPortion: 20, portionLabel: 'four small squares (~20 g)', packageWeight: null, caloriesPerServing: 107, source: 'Typical UK nutrition label value', sourceType: 'food composition reference', sourceUrl: COFID_URL, confidence: 'medium', evidence: [{ value: 107, unit: 'kcal/20g', source: 'British Nutrition Foundation portion guide', url: BNF_URL }] },
  { id: 'pizza-margherita', name: 'Margherita pizza', brand: '', aliases: ['pizza', 'cheese pizza', 'margherita'], category: 'Meals', unit: 'g', kcalPer100: 266, proteinPer100: 11, carbsPer100: 33, fatPer100: 10, defaultPortion: 150, portionLabel: 'one medium slice (~150 g)', packageWeight: null, caloriesPerServing: 399, source: 'CoFID/USDA typical reference; toppings vary', sourceType: 'food composition dataset', sourceUrl: COFID_URL, confidence: 'low', evidence: [{ value: 266, unit: 'kcal/100g', source: 'Generic cheese pizza reference; product recipes vary', url: USDA_URL }] },
  { id: 'burger-beef', name: 'Beef burger', brand: '', aliases: ['hamburger', 'beef hamburger', 'burger patty'], category: 'Meals', unit: 'g', kcalPer100: 250, proteinPer100: 17, carbsPer100: 20, fatPer100: 14, defaultPortion: 180, portionLabel: 'one burger with bun (~180 g)', packageWeight: null, caloriesPerServing: 450, source: 'Generic meal estimate; toppings vary', sourceType: 'food composition dataset', sourceUrl: USDA_URL, confidence: 'low', evidence: [{ value: 450, unit: 'kcal/180g', source: 'Typical burger serving estimate', url: USDA_URL }] },
  { id: 'soup-tomato', name: 'Tomato soup', brand: '', aliases: ['soup tomato', 'tomato soup bowl'], category: 'Meals', unit: 'g', kcalPer100: 50, proteinPer100: 1.5, carbsPer100: 7, fatPer100: 1.7, defaultPortion: 250, portionLabel: 'one bowl (~250 g)', packageWeight: null, caloriesPerServing: 125, source: 'Generic soup estimate; recipe varies', sourceType: 'food composition dataset', sourceUrl: COFID_URL, confidence: 'low', evidence: [{ value: 125, unit: 'kcal/250g', source: 'Typical prepared tomato soup estimate', url: COFID_URL }] }
];

export function normalizeFoodName(value) {
  return String(value || '').normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim().replace(/\s+/g, ' ');
}

function scoreAlias(query, alias) {
  if (query === alias) return 100;
  if (alias.startsWith(query) || query.startsWith(alias)) return 78;
  const q = new Set(query.split(' '));
  const a = new Set(alias.split(' '));
  const shared = [...q].filter(token => a.has(token)).length;
  if (!shared || !query.split(' ').every(token => a.has(token))) return 0;
  return 60 + shared * 2;
}

export function searchLocalNutrition(query, limit = 8) {
  const term = normalizeFoodName(query);
  if (term.length < 2) return [];
  return FOOD_GUIDE.map(food => {
    const aliases = [food.name, ...(food.aliases || [])].map(normalizeFoodName);
    const score = Math.max(0, ...aliases.map(alias => scoreAlias(term, alias)));
    return { ...food, score, isLocal: true };
  }).filter(food => food.score >= 60).sort((a, b) => b.score - a.score || Number(b.brand !== '') - Number(a.brand !== '')).slice(0, limit);
}

export function getFoodGuideRecord(id) {
  const record = FOOD_GUIDE.find(food => food.id === id);
  return record ? { ...record } : null;
}

export function foodGuideRecords() {
  return FOOD_GUIDE.map(food => ({ ...food }));
}

